### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by XDqrkneZ** [winterbuild7074/CrateKeys#2]
19:32:59 [CRITICAL] Unhandled exception executing command 'cratekey dumbass' in cratekey: Undefined property: WinterBuild7074\CrateKeys\Main::$getConfig
19:32:59 [CRITICAL] ErrorException: "Undefined property: WinterBuild7074\CrateKeys\Main::$getConfig" (EXCEPTION) in "/plugins/CrateKeys/src/WinterBuild7074/CrateKeys/Main" at line 32

**Comment by winterbuild7074** [comment]
Fixed – try again now. If there are any other errors or problems, tell me here!
